config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home' => 'static_pages#home', as: :static_pages_home
  root 'static_pages#home'

  devise_for :users, :controllers => {
      invitations: 'users/invitations'
  }
  resources :contacts do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_people do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :countries do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :states do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :users do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :products do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :product_qties do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :qty_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payments do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customer_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customers do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_schedules do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_orders do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_lines do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end

  get 'sales_order/ytd_sales' => 'sales_orders#ytd_sales', as: :ytd_sales

  get 'customer/:id/ajax' => 'customers#ajax', as: :ajax_customer
  get 'sales_order/:id/ajax' => 'sales_orders#ajax', as: :ajax_sales_order

  post 'sales_order/simulation' => 'sales_orders#simulation', as: :sales_order_simulation

  get 'customer/deleted' => 'customers#deleted', as: :deleted_customers
  get 'contact/deleted' => 'contacts#deleted', as: :deleted_contacts
  get 'sales_order/deleted' => 'sales_orders#deleted', as: :deleted_sales_orders
  get 'payment/deleted' => 'payments#deleted', as: :deleted_payments
  get 'product/deleted' => 'products#deleted', as: :deleted_products
  get 'sales_person/deleted' => 'sales_people#deleted', as: :deleted_sales_people
  get 'country/deleted' => 'countries#deleted', as: :deleted_countries
  get 'state/deleted' => 'states#deleted', as: :deleted_states
  get 'customer_status/deleted' => 'customer_statuses#deleted', as: :deleted_customer_statuses
  get 'payment_schedule/deleted' => 'payment_schedules#deleted', as: :deleted_payment_schedules
  get 'payment_type/deleted' => 'payment_types#deleted', as: :deleted_payment_types
  get 'product_qty/deleted' => 'product_qties#deleted', as: :deleted_product_qties
  get 'qty_type/deleted' => 'qty_types#deleted', as: :deleted_qty_types
  get 'sales_order_line/deleted' => 'sales_order_lines#deleted', as: :deleted_sales_order_lines
  get 'sales_order_status/deleted' => 'sales_order_statuses#deleted', as: :deleted_sales_order_statuses
  get 'user/deleted' => 'users#deleted', as: :deleted_users

end

app/controllers/customer_statuses_controller.rb
class CustomerStatusesController < ApplicationController
  before_action :set_customer_status, only: [:show, :edit, :update, :destroy, :hard_delete, :restore]
  before_action :authenticate_user!

  # GET /customer_statuses
  # GET /customer_statuses.json
  def index
    @customer_statuses = CustomerStatus.paginate(:page => params[:page])
  end

  # GET /customer_status/deleted
  def deleted
    @customer_statuses = CustomerStatus.only_deleted.paginate(:page => params[:page])
  end

  # POST /customer_status/:id/delete
  def hard_delete
    @customer_status.really_destroy!
    redirect_to deleted_customer_statuses_path, notice: 'Customer status permanently deleted'
  end

  # POST /customer_status/:id/reinstate
  def restore
    @customer_status.restore
    redirect_to deleted_customer_statuses_path, notice: 'Customer status reinstated'
  end

  # GET /customer_statuses/1
  # GET /customer_statuses/1.json
  def show
  end

  # GET /customer_statuses/new
  def new
    @customer_status = CustomerStatus.new
  end

  # GET /customer_statuses/1/edit
  def edit
  end

  # POST /customer_statuses
  # POST /customer_statuses.json
  def create
    @customer_status = CustomerStatus.new(customer_status_params)

    respond_to do |format|
      if @customer_status.save
        format.html { redirect_to @customer_status, notice: 'Customer status was successfully created.' }
        format.json { render :show, status: :created, location: @customer_status }
      else
        format.html { render :new }
        format.json { render json: @customer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_statuses/1
  # PATCH/PUT /customer_statuses/1.json
  def update
    respond_to do |format|
      if @customer_status.update(customer_status_params)
        format.html { redirect_to @customer_status, notice: 'Customer status was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_status }
      else
        format.html { render :edit }
        format.json { render json: @customer_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_statuses/1
  # DELETE /customer_statuses/1.json
  def destroy
    @customer_status.destroy
    respond_to do |format|
      format.html { redirect_to customer_statuses_url, notice: 'Customer status was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_status
      @customer_status = CustomerStatus.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_status_params
      params.require(:customer_status).permit(:status_desc)
    end
end

app/helpers/customer_statuses_helper.rb
module CustomerStatusesHelper
end

app/views/customer_statuses/_form.html.erb
<%= form_for(@customer_status) do |f| %>
  <% if @customer_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_status.errors.count, "error") %> prohibited this customer_status from being saved:</h2>

      <ul>
      <% @customer_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_desc %><br>
    <%= f.text_field :status_desc %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class =>"btn btn-primary", style: "color: white" %>
  </div>
<% end %>

app/views/customer_statuses/deleted.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customer Statuses</h1>

<table class="table-condensed table-striped">
  <thead>
  <tr>
    <th>Status Description</th>
    <th>Deleted At</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @customer_statuses.each do |customer_status| %>
      <tr>
        <td><%= customer_status.status_desc %></td>
        <td><%= customer_status.deleted_at.to_s.to_date %></td>
        <td><%= link_to 'Show', customer_status %></td>
        <td><%= link_to 'Restore', restore_customer_status_path(customer_status), method: :post, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Permanently Delete', hard_delete_customer_status_path(customer_status), method: :post, data: { confirm: 'Are you sure? You cannot undo this action.' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @customer_statuses, :model => 'customer_status' %>
  </div>
  <%= will_paginate @customer_statuses, :container => false %>
</div>

<br>

<%= link_to 'Active Customer Statuses', customer_statuses_path, :class =>"btn btn-primary", style: "color: white" %>

app/views/customer_statuses/edit.html.erb
<h1>Editing Customer Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_status, :class =>"btn btn-primary", style: "color: white" %> |
<%= link_to 'Back', customer_statuses_path, :class =>"btn btn-primary", style: "color: white" %>

app/views/customer_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Customer Statuses</h1>

<table class="table-condensed table-striped">
  <thead>
    <tr>
      <th>Status Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_statuses.each do |customer_status| %>
      <tr>
        <td><%= customer_status.status_desc %></td>
        <td><%= link_to 'Show', customer_status %></td>
        <td><%= link_to 'Edit', edit_customer_status_path(customer_status) %></td>
        <td><%= link_to 'Delete', customer_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @customer_statuses, :model => 'customer_status' %>
  </div>
  <%= will_paginate @customer_statuses, :container => false %>
</div>

<br>

<%= link_to 'New Customer status', new_customer_status_path, :class =>"btn btn-primary", style: "color: white" %>
<%= link_to 'Deleted', deleted_customer_statuses_path, :class =>"btn btn-primary", style: "color: white" %>

app/views/customer_statuses/new.html.erb
<h1>New Customer Status</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_statuses_path, :class =>"btn btn-primary", style: "color: white" %>

app/views/customer_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status desc:</strong>
  <%= @customer_status.status_desc %>
</p>

<%= link_to 'Edit', edit_customer_status_path(@customer_status), :class =>"btn btn-primary", style: "color: white" %> |
<%= link_to 'Back', customer_statuses_path, :class =>"btn btn-primary", style: "color: white" %>