config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home' => 'static_pages#home', as: :static_pages_home
  root 'static_pages#home'

  devise_for :users, :controllers => {
      invitations: 'users/invitations'
  }
  resources :contacts do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_people do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :countries do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :states do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :users do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :products do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :product_qties do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :qty_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payments do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customer_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customers do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_schedules do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_orders do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_lines do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end

  get 'sales_order/ytd_sales' => 'sales_orders#ytd_sales', as: :ytd_sales

  get 'customer/:id/ajax' => 'customers#ajax', as: :ajax_customer
  get 'sales_order/:id/ajax' => 'sales_orders#ajax', as: :ajax_sales_order

  post 'sales_order/simulation' => 'sales_orders#simulation', as: :sales_order_simulation

  get 'customer/deleted' => 'customers#deleted', as: :deleted_customers
  get 'contact/deleted' => 'contacts#deleted', as: :deleted_contacts
  get 'sales_order/deleted' => 'sales_orders#deleted', as: :deleted_sales_orders
  get 'payment/deleted' => 'payments#deleted', as: :deleted_payments
  get 'product/deleted' => 'products#deleted', as: :deleted_products
  get 'sales_person/deleted' => 'sales_people#deleted', as: :deleted_sales_people
  get 'country/deleted' => 'countries#deleted', as: :deleted_countries
  get 'state/deleted' => 'states#deleted', as: :deleted_states
  get 'customer_status/deleted' => 'customer_statuses#deleted', as: :deleted_customer_statuses
  get 'payment_schedule/deleted' => 'payment_schedules#deleted', as: :deleted_payment_schedules
  get 'payment_type/deleted' => 'payment_types#deleted', as: :deleted_payment_types
  get 'product_qty/deleted' => 'product_qties#deleted', as: :deleted_product_qties
  get 'qty_type/deleted' => 'qty_types#deleted', as: :deleted_qty_types
  get 'sales_order_line/deleted' => 'sales_order_lines#deleted', as: :deleted_sales_order_lines
  get 'sales_order_status/deleted' => 'sales_order_statuses#deleted', as: :deleted_sales_order_statuses
  get 'user/deleted' => 'users#deleted', as: :deleted_users

end

app/controllers/qty_types_controller.rb
class QtyTypesController < ApplicationController
  before_action :set_qty_type, only: [:show, :edit, :update, :destroy, :hard_delete, :restore]

  # GET /qty_types
  # GET /qty_types.json
  def index
    @qty_types = QtyType.paginate(:page => params[:page])
  end

  # GET /qty_type/deleted
  def deleted
    @qty_types = QtyType.only_deleted.order(qty_type_name: :asc).paginate(:page => params[:page])
  end

  # POST /qty_type/:id/delete
  def hard_delete
    @qty_type.really_destroy!
    redirect_to deleted_qty_types_path, notice: 'Quantity Type permanently deleted'
  end

  # POST /qty_type/:id/reinstate
  def restore
    @qty_type.restore
    redirect_to deleted_qty_types_path, notice: 'Quantity Type reinstated'
  end

  # GET /qty_types/1
  # GET /qty_types/1.json
  def show
  end

  # GET /qty_types/new
  def new
    @qty_type = QtyType.new
  end

  # GET /qty_types/1/edit
  def edit
  end

  # POST /qty_types
  # POST /qty_types.json
  def create
    @qty_type = QtyType.new(qty_type_params)

    respond_to do |format|
      if @qty_type.save
        format.html { redirect_to @qty_type, notice: 'Qty type was successfully created.' }
        format.json { render :show, status: :created, location: @qty_type }
      else
        format.html { render :new }
        format.json { render json: @qty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qty_types/1
  # PATCH/PUT /qty_types/1.json
  def update
    respond_to do |format|
      if @qty_type.update(qty_type_params)
        format.html { redirect_to @qty_type, notice: 'Qty type was successfully updated.' }
        format.json { render :show, status: :ok, location: @qty_type }
      else
        format.html { render :edit }
        format.json { render json: @qty_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qty_types/1
  # DELETE /qty_types/1.json
  def destroy
    @qty_type.destroy
    respond_to do |format|
      format.html { redirect_to qty_types_url, notice: 'Qty type was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qty_type
      @qty_type = QtyType.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qty_type_params
      params.require(:qty_type).permit(:qty_type_name, :deleted_at)
    end
end

app/helpers/qty_types_helper.rb
module QtyTypesHelper
end

app/views/qty_types/_form.html.erb
<%= form_for(@qty_type) do |f| %>
  <% if @qty_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qty_type.errors.count, "error") %> prohibited this qty_type from being saved:</h2>

      <ul>
      <% @qty_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :qty_type_name, 'Quantity Type' %><br>
    <%= f.text_field :qty_type_name %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Quantity Type', :class => 'btn btn-primary', style: "color: white"%>
  </div>
<% end %>

app/views/qty_types/deleted.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Qty Types</h1>

<table class="table-condensed table-striped">
  <thead>
  <tr>
    <th>Qty Type Name</th>
    <th>Deleted At</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @qty_types.each do |qty_type| %>
      <tr>
        <td><%= qty_type.qty_type_name %></td>
        <td><%= qty_type.deleted_at.to_s.to_date %></td>
        <td><%= link_to 'Show', qty_type %></td>
        <td><%= link_to 'Restore', restore_qty_type_path(qty_type), method: :post, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Permanently Delete', hard_delete_qty_type_path(qty_type), method: :post, data: { confirm: 'Are you sure? You cannot undo this action.' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @qty_types, :model => 'qty_types' %>
  </div>
  <%= will_paginate @qty_types, :container => false %>
</div>

<br>

<%= link_to 'Active Quantity Types', qty_types_path, :class => 'btn btn-primary', style: "color: white" %>

app/views/qty_types/edit.html.erb
<h1>Editing Qty Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @qty_type, :class => 'btn btn-primary', style: "color: white" %> |
<%= link_to 'Back', qty_types_path, :class => 'btn btn-primary', style: "color: white" %>

app/views/qty_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quantity Types</h1>

<table class="table-condensed table-striped">
  <thead>
    <tr>
      <th>Quantity Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qty_types.each do |qty_type| %>
      <tr>
        <td><%= qty_type.qty_type_name %></td>
        <td><%= link_to 'Show', qty_type %></td>
        <td><%= link_to 'Edit', edit_qty_type_path(qty_type) %></td>
        <td><%= link_to 'Delete', qty_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @qty_types, :model => 'qty_types' %>
  </div>
  <%= will_paginate @qty_types, :container => false %>
</div>

<br>

<%= link_to 'New Quantity type', new_qty_type_path, :class => 'btn btn-primary', style: "color: white" %>
<%= link_to 'Deleted', deleted_qty_types_path, :class => 'btn btn-primary', style: "color: white" %>

app/views/qty_types/new.html.erb
<h1>New Quantity Type</h1>

<%= render 'form' %>

<%= link_to 'Back', qty_types_path, :class => 'btn btn-primary', style: "color: white" %>

app/views/qty_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qty type name:</strong>
  <%= @qty_type.qty_type_name %>
</p>


<%= link_to 'Edit', edit_qty_type_path(@qty_type), :class => 'btn btn-primary', style: "color: white" %> |
<%= link_to 'Back', qty_types_path, :class => 'btn btn-primary', style: "color: white" %>