config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home' => 'static_pages#home', as: :static_pages_home
  root 'static_pages#home'

  devise_for :users, :controllers => {
      invitations: 'users/invitations'
  }
  resources :contacts do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_people do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :countries do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :states do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :users do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :products do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :product_qties do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :qty_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payments do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customer_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customers do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_schedules do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_orders do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_lines do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end

  get 'sales_order/ytd_sales' => 'sales_orders#ytd_sales', as: :ytd_sales

  get 'customer/:id/ajax' => 'customers#ajax', as: :ajax_customer
  get 'sales_order/:id/ajax' => 'sales_orders#ajax', as: :ajax_sales_order

  post 'sales_order/simulation' => 'sales_orders#simulation', as: :sales_order_simulation

  get 'customer/deleted' => 'customers#deleted', as: :deleted_customers
  get 'contact/deleted' => 'contacts#deleted', as: :deleted_contacts
  get 'sales_order/deleted' => 'sales_orders#deleted', as: :deleted_sales_orders
  get 'payment/deleted' => 'payments#deleted', as: :deleted_payments
  get 'product/deleted' => 'products#deleted', as: :deleted_products
  get 'sales_person/deleted' => 'sales_people#deleted', as: :deleted_sales_people
  get 'country/deleted' => 'countries#deleted', as: :deleted_countries
  get 'state/deleted' => 'states#deleted', as: :deleted_states
  get 'customer_status/deleted' => 'customer_statuses#deleted', as: :deleted_customer_statuses
  get 'payment_schedule/deleted' => 'payment_schedules#deleted', as: :deleted_payment_schedules
  get 'payment_type/deleted' => 'payment_types#deleted', as: :deleted_payment_types
  get 'product_qty/deleted' => 'product_qties#deleted', as: :deleted_product_qties
  get 'qty_type/deleted' => 'qty_types#deleted', as: :deleted_qty_types
  get 'sales_order_line/deleted' => 'sales_order_lines#deleted', as: :deleted_sales_order_lines
  get 'sales_order_status/deleted' => 'sales_order_statuses#deleted', as: :deleted_sales_order_statuses
  get 'user/deleted' => 'users#deleted', as: :deleted_users

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :payment_type
  belongs_to :sales_order

  validates :sales_order, :payment_date, :payment_amt, :presence => true
  validates :payment_amt, :numericality => {:greater_than_or_equal_to => 0}
  validate :payment_amt_must_be_less_than_or_equal_to_order_balance_due

  def payment_amt_must_be_less_than_or_equal_to_order_balance_due
    payment_max = self.sales_order.order_balance_due
    self.errors.add(:payment_amt, "Payment must be less than the amount due") unless self.payment_amt <= payment_max
  end

  before_restore :restore_callback

  def restore_callback

    self.sales_order.order_balance_due -= self.payment_amt
    self.sales_order.order_balance_received += self.payment_amt

    if Integer(self.payment_amt * 100) == Integer(self.sales_order.order_balance_due * 100)
      self.sales_order.sales_order_status_id = 3
    elsif self.sales_order.sales_order_status_id == 1
      self.sales_order.sales_order_status_id = 2
    elsif Integer(self.sales_order.order_balance_due * 100) == 0
      self.sales_order.sales_order_status_id = 3
    end

    self.sales_order.save
  end

  after_restore do
    if Integer(self.sales_order.order_balance_received * 100) > Integer(self.sales_order.order_grand_total * 100)
      self.destroy
    elsif Integer(self.sales_order.order_balance_due * 100) == 0
      pmt = self.sales_order.latest_payment
      logger.info pmt
      pmt.payment_type_id = 3
      logger.info pmt.payment_type_id
      pmt.save
    end
  end

  before_save do
    if Integer(self.payment_amt * 100) == Integer(self.sales_order.order_grand_total * 100)
      self.payment_type_id = 2
    elsif Integer(self.payment_amt * 100) == Integer(self.sales_order.order_balance_due * 100)
      self.payment_type_id = 3
    else
      self.payment_type_id = 1
    end
  end

  after_save do
    if Integer(self.payment_amt * 100) == Integer(self.sales_order.order_balance_due * 100)
      self.sales_order.sales_order_status_id = 3
      self.sales_order.save
    elsif self.sales_order.sales_order_status_id == 1
      self.sales_order.sales_order_status_id = 2
      self.sales_order.save
    end
  end

  after_destroy do
    self.sales_order.order_balance_due += self.payment_amt
    self.sales_order.order_balance_received -= self.payment_amt

    if Integer(self.sales_order.order_balance_received * 100) == 0
      self.sales_order.sales_order_status_id = 1
    else
      self.sales_order.sales_order_status_id = 2
    end

    self.sales_order.payments.each do |pmt|
      if pmt.payment_type_id == 3
        pmt.payment_type_id == 1
        pmt.save
      end
    end

    self.sales_order.save

  end

  trigger.after(:insert) do
      "UPDATE sales_orders SET order_balance_received = order_balance_received + NEW.payment_amt WHERE sales_orders.id = NEW.sales_order_id"
  end
  trigger.after(:insert) do
    "UPDATE sales_orders SET order_balance_due = order_balance_due - NEW.payment_amt WHERE sales_orders.id = NEW.sales_order_id"
  end

  trigger.after(:update).of(:payment_amt) do
    "UPDATE sales_orders SET order_balance_received = order_balance_received + ( NEW.payment_amt - OLD.payment_amt ) WHERE sales_orders.id = NEW.sales_order_id"
  end

  trigger.after(:update).of(:payment_amt) do
    "UPDATE sales_orders SET order_balance_due = order_balance_due - ( NEW.payment_amt - OLD.payment_amt ) WHERE sales_orders.id = NEW.sales_order_id"
  end

  trigger.after(:destroy) do
    "UPDATE sales_orders SET order_balance_received = order_balance_received - OLD.payment_amt WHERE sales_orders.id = OLD.sales_order_id"
  end

  trigger.after(:destroy) do
    "UPDATE sales_orders SET order_balance_due = order_balance_due + OLD.payment_amt WHERE sales_orders.id = OLD.sales_order_id"
  end
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base
  acts_as_paranoid

  has_many :payments

  validates :type_desc, presence: true
  validates :type_desc, length: { maximum: 50, too_long: "%{count} is the maximum characters allowed"}
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy, :hard_delete, :restore]
  before_action :authenticate_admin!, only: [:deleted, :hard_delete, :restore]

  helper_method :get_customer_from_so, :customers_with_credit, :get_so_from_so

  # GET /payments
  # GET /payments.json
  def index
    @q = Payment.ransack(params[:q])
    @payments = @q.result.paginate(:page => params[:page])
    @all_payments = Payment.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="ORCA_Payments_List_'+Date.today.to_s+'.xlsx"'
      }
    end
  end

  # GET /payment/deleted
  def deleted
    @payments = Payment.only_deleted.paginate(:page => params[:page])
  end

  # POST /payment/:id/delete
  def hard_delete
    @payment.really_destroy!
    redirect_to deleted_payments_path, notice: 'Payment permanently deleted'
  end

  # POST /payment/:id/reinstate
  def restore
    @payment.restore
    redirect_to deleted_payments_path, notice: 'Payment reinstated'
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    # @customers = Customer.all
    @so = -1
    if params[:so]
      @so = params[:so]
    end
  end

  # GET /payments/1/edit
  def edit
    @so = -1
    if params[:so]
      @so = params[:so]
    end
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # helper methods
  def get_customer_from_so(so)
    SalesOrder.find(so).customer.customer_name
  end
  def get_so_from_so(so)
    SalesOrder.find(so)
  end
  def customers_with_credit
    Customer.select(:id, :customer_name, 'SUM(order_balance_due)', :is_approved).joins(:sales_orders).having('SUM(order_balance_due) > 0.01 AND is_approved = true').group(:id, :customer_name, :is_approved).distinct
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:payment_type_id, :sales_order_id, :purchase_order_id, :payment_date, :payment_amt)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field sales-order-select">
    <%= f.label :customers_state, 'Select a Customer: ' %>
    <% if Integer(@so) > 0 %>
        <%= select_tag 'customer', options_from_collection_for_select(customers_with_credit, :customer_name, :customer_name, :selected => get_customer_from_so(@so)) %>
    <% else %>
        <%= select_tag 'customer', options_from_collection_for_select(customers_with_credit, :customer_name, :customer_name), :include_blank => true %>
    <% end %>
    <button class="btn btn-info" type="button" id="clear_sales_order_filter">Clear Filter</button>
    <br>
    <br>
    <div class="row">
    <%= f.label :sales_order_id, 'Sales Order' %><% if Integer(@so) > 0 %><%= link_to 'Back to Sales Order', sales_order_path(@so), :class => 'btn btn-primary', style: 'color: white; margin-left: 10px' %><% end %><br>
    <%= f.grouped_collection_select :sales_order_id, customers_with_credit, :sales_orders_with_balance, :customer_name, :id, :id, {:selected => @so, :include_blank => true} %>
    </div>
  </div>

  <% if Integer(@so) > 0 %>
    <div class="field so-balance-due">
      <div class="field sales_order">
        <label id="so_credit_label">Remaining Balance</label>
        <input readonly="readonly" type="text" id="so_credit" number="<%= '%.2f' % get_so_from_so(@so).order_balance_due %>" value="<%= to_indian_currency get_so_from_so(@so).order_balance_due %>">
      </div>
    </div>
  <% else %>
    <div class="field so-balance-due" style="display: none">
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payment_date, "Payment Date" %><br>
    <%= f.text_field :payment_date, {:id => 'datepicker', :readonly => true, :value => Date.today } %>
  </div>
  <div class="field">
    <%= f.label :payment_amt, "Payment Amount" %><br>
    <%= f.text_field :payment_amt %> <button type="button" class="btn btn-info" id="remainder">Remaining Balance</button>
  </div>

    <div class="actions">
    <%= f.submit "Create Payment", :class =>"btn btn-primary", style: "color: white; background: black" %>
  </div>
<% end %>

app/views/payments/deleted.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Deleted Payments</h1>

<table class="table-condensed table-striped">
  <thead>
  <tr>
    <th>Payment Status</th>
    <th>Sales Order ID</th>
    <th>Payment Date</th>
    <th>Payment Amount</th>
    <th>Deleted At</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.payment_type.type_desc %></td>
        <td><%= payment.sales_order_id %></td>
        <td><%= payment.payment_date %></td>
        <td><%= to_indian_currency payment.payment_amt %></td>
        <td><%= payment.deleted_at.to_s.to_date %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Restore', restore_payment_path(payment), method: :post, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Permanently Delete', hard_delete_payment_path(payment), method: :post, data: { confirm: 'Are you sure? This action cannot be undone.' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @payments %>
  </div>
  <%= will_paginate @payments, :container => false %>
</div>

<br>

<%= link_to 'Active Payments', payments_path, :class => "btn btn-primary", style: "color: white"%>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment, :class => 'btn btn-primary', style: "color: white" %> |
<%= link_to 'Back', payments_path, :class => 'btn btn-primary', style: "color: white" %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container ">
<h1>Listing Payments</h1>
<br>
<h4>Filters:</h4>
<%= search_form_for @q do |f| %>
    <div class="col-md-3" id="col1">
      <%= f.label :payment_type, 'Payment Status:' %>
      <%= f.collection_select :payment_type_id_eq, PaymentType.joins(:payments).distinct.order(:type_desc => :asc), :id, :type_desc, include_blank: :true %>
      <br>
      <br>
      <%= f.label :sales_order, 'Sales Order Number:' %>
      <%= f.collection_select :sales_order_id_eq, SalesOrder.joins(:payments).distinct.order(:id => :asc), :id, :id, include_blank: :true %>
      <br>
      <%= f.submit 'Search', :class=>'btn btn-primary'%> <%= link_to 'Clear Filters', payments_path, {:class =>'btn btn-info', style: "color: white"} %>
      <br>
      <br>
    </div>
    <div class="col-md-8" id="col2">
      <%= f.label :payment_date, 'Payment Date:' %>
      <%= f.text_field :payment_date_gteq, {:class => 'datepicker'} %> to <%= f.text_field :payment_date_lteq, {:class => 'datepicker'} %>
      <br>
      <br>
      <%= f.label :customer_name, 'Customer Name' %>
      <%= f.collection_select :sales_order_customer_id_eq, Customer.joins(:payments).distinct.order(:customer_name => :asc), :id, :customer_name, :include_blank => true %>
    </div>
    <br>
    <br>

<% end %>
<br>
</div>
<div class="container text-center">
<table class="table-condensed table-striped ">
  <thead>
    <tr>
      <th><%= sort_link @q, :sales_order_customer_customer_name, 'Customer Name' %></th>
      <th><%= sort_link @q, :payment_type_type_desc, 'Payment Status' %></th>
      <th><%= sort_link @q, :sales_order_id, 'Sales Order Number' %></th>
      <th><%= sort_link @q, :payment_date, 'Payment Date' %></th>
      <th><%= sort_link @q, :payment_amt, 'Amount' %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody class="text-left">
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.sales_order.customer.customer_name %></td>
        <td><%= payment.payment_type.type_desc %></td>
        <td class="text-center"><%= link_to payment.sales_order_id, sales_order_path(payment.sales_order) %></td>
        <td><%= l payment.payment_date %></td>
        <td class="text-right"><%= to_indian_currency(payment.payment_amt) %></td>
        <td><%= link_to 'Show', payment %></td>
        <!--<td><%= link_to 'Edit', edit_payment_path(payment) %></td>-->
        <td><%= link_to 'Delete', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="col-md-2"></div>
<div class="col-md-4 text-left">
<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @payments, :model => 'payment' %>
  </div>
  <%= will_paginate @payments, :container => false %>
</div>

<br>

<%= link_to 'Download as .xlsx', payments_path(format: :xlsx), :class => "btn btn-primary", style: "color: white" %>
</div>

app/views/payments/new.html.erb
<h1>New Payment</h1>
<div class="container pull-left">
<%= render 'form' %>

<%= link_to 'Back to Payments Listing', payments_path, :class=>'btn btn-primary', style: "color: white" %>
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment Status:</strong>
  <%= @payment.payment_type.type_desc %>
</p>

<p>
  <strong>Sales Order Number:</strong>
  <%= link_to @payment.sales_order_id, sales_order_path(@payment.sales_order_id) %>
</p>

<p>
  <strong>Sales Order Balance Remaining:</strong>
  <%= to_indian_currency @payment.sales_order.order_balance_due %>
</p>

<p>
  <strong>Payment Date:</strong>
  <%= @payment.payment_date %>
</p>

<p>
  <strong>Payment Amount:</strong>
  <%= to_indian_currency @payment.payment_amt %>
</p>

<%= link_to 'Add Another Payment', new_payment_path(:so => @payment.sales_order), :class => 'btn btn-primary' %>
<%= link_to 'Back to Payments', payments_path, :class => 'btn btn-primary', style: "color: white" %>