config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home' => 'static_pages#home', as: :static_pages_home
  root 'static_pages#home'

  devise_for :users, :controllers => {
      invitations: 'users/invitations'
  }
  resources :contacts do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_people do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :countries do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :states do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :users do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :products do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :product_qties do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :qty_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payments do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_types do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customer_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :customers do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :payment_schedules do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_orders do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_lines do
    member do
      post :hard_delete
      post :restore
    end
  end
  resources :sales_order_statuses do
    member do
      post :hard_delete
      post :restore
    end
  end

  get 'sales_order/ytd_sales' => 'sales_orders#ytd_sales', as: :ytd_sales

  get 'customer/:id/ajax' => 'customers#ajax', as: :ajax_customer
  get 'sales_order/:id/ajax' => 'sales_orders#ajax', as: :ajax_sales_order

  post 'sales_order/simulation' => 'sales_orders#simulation', as: :sales_order_simulation

  get 'customer/deleted' => 'customers#deleted', as: :deleted_customers
  get 'contact/deleted' => 'contacts#deleted', as: :deleted_contacts
  get 'sales_order/deleted' => 'sales_orders#deleted', as: :deleted_sales_orders
  get 'payment/deleted' => 'payments#deleted', as: :deleted_payments
  get 'product/deleted' => 'products#deleted', as: :deleted_products
  get 'sales_person/deleted' => 'sales_people#deleted', as: :deleted_sales_people
  get 'country/deleted' => 'countries#deleted', as: :deleted_countries
  get 'state/deleted' => 'states#deleted', as: :deleted_states
  get 'customer_status/deleted' => 'customer_statuses#deleted', as: :deleted_customer_statuses
  get 'payment_schedule/deleted' => 'payment_schedules#deleted', as: :deleted_payment_schedules
  get 'payment_type/deleted' => 'payment_types#deleted', as: :deleted_payment_types
  get 'product_qty/deleted' => 'product_qties#deleted', as: :deleted_product_qties
  get 'qty_type/deleted' => 'qty_types#deleted', as: :deleted_qty_types
  get 'sales_order_line/deleted' => 'sales_order_lines#deleted', as: :deleted_sales_order_lines
  get 'sales_order_status/deleted' => 'sales_order_statuses#deleted', as: :deleted_sales_order_statuses
  get 'user/deleted' => 'users#deleted', as: :deleted_users

end

app/models/sales_order_line.rb
class SalesOrderLine < ActiveRecord::Base
  acts_as_paranoid

  belongs_to :sales_order, :dependent => :destroy
  belongs_to :product_qty
  belongs_to :product

  # only validate sales order on update because it is a nested field in Sales Order
  validates :sales_order, :presence => true, :on => :update

  validates :product_qty, :product, :qty_requested, :qty_approved, :unit_price, :product_total, :presence => true
  validates :qty_requested, :qty_approved, :numericality => {:only_integer => true, :greater_than_or_equal_to => 0}
  validates :unit_price, :numericality => true

  before_validation do
    if self.qty_approved == nil
      self.qty_approved = self.qty_requested
    end
  end

end

app/controllers/sales_order_lines_controller.rb
class SalesOrderLinesController < ApplicationController
  before_action :set_sales_order_line, only: [:show, :edit, :update, :destroy, :hard_delete, :restore]

  # GET /sales_order_lines
  # GET /sales_order_lines.json
  def index
    @sales_order_lines = SalesOrderLine.paginate(:page => params[:page])
  end

  # GET /sales_order_line/deleted
  def deleted
    @sales_order_lines = SalesOrderLine.only_deleted.paginate(:page => params[:page])
  end

  # POST /sales_order_line/:id/delete
  def hard_delete
    @sales_order_line.really_destroy!
    redirect_to deleted_sales_order_lines_path, notice: 'Sales Order Line permanently deleted'
  end

  # POST /sales_order_line/:id/reinstate
  def restore
    @sales_order_line.restore
    redirect_to deleted_sales_order_lines_path, notice: 'Sales Order Line reinstated'
  end

  # GET /sales_order_lines/1
  # GET /sales_order_lines/1.json
  def show
  end

  # GET /sales_order_lines/new
  def new
    @sales_order_line = SalesOrderLine.new
  end

  # GET /sales_order_lines/1/edit
  def edit
  end

  # POST /sales_order_lines
  # POST /sales_order_lines.json
  def create
    @sales_order_line = SalesOrderLine.new(sales_order_line_params)

    respond_to do |format|
      if @sales_order_line.save
        format.html { redirect_to @sales_order_line, notice: 'Sales Order line was successfully created.' }
        format.json { render :show, status: :created, location: @sales_order_line }
      else
        format.html { render :new }
        format.json { render json: @sales_order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_order_lines/1
  # PATCH/PUT /sales_order_lines/1.json
  def update
    respond_to do |format|
      if @sales_order_line.update(sales_order_line_params)
        format.html { redirect_to @sales_order_line, notice: 'Sales Order line was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_order_line }
      else
        format.html { render :edit }
        format.json { render json: @sales_order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_order_lines/1
  # DELETE /sales_order_lines/1.json
  def destroy
    @sales_order_line.destroy
    respond_to do |format|
      format.html { redirect_to sales_order_lines_url, notice: 'Sales Order line was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_order_line
      @sales_order_line = SalesOrderLine.with_deleted.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_order_line_params
      params.require(:sales_order_line).permit(:product_id, :qty_requested, :qty_approved, :unit_price, :product_total, :deleted_at)
    end
end

app/helpers/sales_order_lines_helper.rb
module SalesOrderLinesHelper
end

app/views/sales_order_lines/_form.html.erb
<%= form_for(@sales_order_line) do |f| %>
  <% if @sales_order_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sales_order_line.errors.count, "error") %> prohibited this sales_order_line from being saved:</h2>

      <ul>
      <% @sales_order_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :qty_requested %><br>
    <%= f.number_field :qty_requested %>
  </div>
  <div class="field">
    <%= f.label :qty_approved %><br>
    <%= f.number_field :qty_approved %>
  </div>
  <div class="field">
    <%= f.label :unit_price %><br>
    <%= f.text_field :unit_price %>
  </div>
  <div class="field">
    <%= f.label :product_total %><br>
    <%= f.text_field :product_total %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br>
    <%= f.datetime_select :deleted_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales_order_lines/deleted.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales Order Lines</h1>

<table class="table table-condensed">
  <thead>
  <tr>
    <th>Sales Order</th>
    <th>Product</th>
    <th>Size</th>
    <th>Qty requested</th>
    <th>Qty approved</th>
    <th>Unit price</th>
    <th>Product total</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @sales_order_lines.each do |sales_order_line| %>
      <tr>
        <td><%= sales_order_line.sales_order_id %></td>
        <td><%= sales_order_line.product_qty.product.product_name %></td>
        <td><%= sales_order_line.product_qty.description %></td>
        <td style="text-align:center"><%= sales_order_line.qty_requested %></td>
        <td style="text-align:center"><%= sales_order_line.qty_approved %></td>
        <td style="text-align:right"><%= sprintf( '%0.02f', sales_order_line.unit_price) %></td>
        <td style="text-align:right"><%= sprintf( '%0.02f', sales_order_line.product_total) %></td>
        <td><%= link_to 'Show', sales_order_line %></td>
        <td><%= link_to 'Restore', restore_sales_order_line_path(sales_order_line), method: :post, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Permanently Delete', hard_delete_sales_order_line_path(sales_order_line), method: :post, data: { confirm: 'Are you sure? You cannot undo this action.' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @sales_order_lines, :model => 'sales_order_line' %>
  </div>
  <%= will_paginate @sales_order_lines, :container => false %>
</div>

<br>

<%= link_to 'Active', sales_order_lines_path %>

app/views/sales_order_lines/edit.html.erb
<h1>Editing Sales Order Line</h1>

<%= render 'form' %>

<%= link_to 'Show', @sales_order_line %> |
<%= link_to 'Back', sales_order_lines_path %>

app/views/sales_order_lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales Order Lines</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Sales Order</th>
      <th>Product</th>
      <th>Size</th>
      <th>Qty requested</th>
      <th>Qty approved</th>
      <th>Unit price</th>
      <th>Product total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_order_lines.each do |sales_order_line| %>
      <tr>
        <td><%= sales_order_line.sales_order_id %></td>
        <td><%= sales_order_line.product_qty.product.product_name %></td>
        <td><%= sales_order_line.product_qty.description %></td>
        <td style="text-align:center"><%= sales_order_line.qty_requested %></td>
        <td style="text-align:center"><%= sales_order_line.qty_approved %></td>
        <td style="text-align:right"><%= '%.2f' % sales_order_line.unit_price %></td>
        <td style="text-align:right"><%= '%.2f' % sales_order_line.product_total %></td>
        <td><%= link_to 'Show', sales_order_line %></td>
        <td><%= link_to 'Edit', edit_sales_order_line_path(sales_order_line) %></td>
        <td><%= link_to 'Delete', sales_order_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="digg_pagination">
  <div class="page_info">
    <%= page_entries_info @sales_order_lines, :model => 'sales_order_line' %>
  </div>
  <%= will_paginate @sales_order_lines, :container => false %>
</div>

<br>

<%= link_to 'New Sales order line', new_sales_order_line_path %> <%= link_to 'Deleted', deleted_sales_order_lines_path %>

app/views/sales_order_lines/new.html.erb
<h1>New Sales Order Line</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_order_lines_path %>

app/views/sales_order_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @sales_order_line.product_id %>
</p>

<p>
  <strong>Qty requested:</strong>
  <%= @sales_order_line.qty_requested %>
</p>

<p>
  <strong>Qty approved:</strong>
  <%= @sales_order_line.qty_approved %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= '%.2f' % @sales_order_line.unit_price %>
</p>

<p>
  <strong>Product total:</strong>
  <%= '%.2f' % @sales_order_line.product_total %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @sales_order_line.deleted_at %>
</p>

<%= link_to 'Edit', edit_sales_order_line_path(@sales_order_line) %> |
<%= link_to 'Back', sales_order_lines_path %>